USE SHOP;

CREATE TABLE IF NOT EXISTS ITEMS (
  ID INT NOT NULL AUTO_INCREMENT,
  ITEM_NAME VARCHAR(255) NOT NULL,
  BEST_BEFORE DATE,
  SP FLOAT NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS INVENTORY (
  ID INT NOT NULL,
  QUANTITY INT NOT NULL,
  MFG_DATE DATE NOT NULL,
  EXP_DATE DATE,
  EXPIRED CHAR(3),
  ARRIVAL DATE NOT NULL,
  SELL_DATE DATE,
  FOREIGN KEY(ID) REFERENCES ITEMS(ID)
);

