USE SHOP;

CREATE TABLE IF NOT EXISTS ITEMS (
  ID INT NOT NULL AUTO_INCREMENT,
  ITEM_NAME VARCHAR(255) NOT NULL,
  SP FLOAT NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS INVENTORY (
  ID INT NOT NULL,
  QUANTITY INT NOT NULL,
  FOREIGN KEY(ID) REFERENCES ITEMS(ID)
);

CREATE TABLE IF NOT EXISTS SOLD (
  ID INT NOT NULL,
  QUANTITY INT NOT NULL,
  FOREIGN KEY(ID) REFERENCES ITEMS(ID)
);

CREATE TABLE IF NOT EXISTS BOUGHT (
  ID INT NOT NULL,
  QUANTITY INT NOT NULL,
  FOREIGN KEY(ID) REFERENCES ITEMS(ID)
);

CREATE TABLE IF NOT EXISTS EXP_ITEMS (
  ID INT NOT NULL,
  QUANTITY INT NOT NULL,
  FOREIGN KEY(ID) REFERENCES ITEMS(ID)
);

CREATE TABLE IF NOT EXISTS DAILY_REPORT (
  REPORT_DATE DATE NOT NULL,
  OPENNING BLOB,
  CLOSING BLOB,
  PRIMARY KEY(REPORT_DATE)
);
